### PR TITLE
[AMD-AIE] Update mlir-air and mlir-aie submodules

### PR DESCRIPTION
**Pull request by Abhishek-Varma**
-- Bring in changes to mlir-air and mlir-aie submodules due to latest
   IREE LLVM bump.

Signed-off-by: Abhishek Varma <abhvarma@amd.com>

### CODE REVIEW

**Comment by newling** [comment]
There is a change in mlir-air main for updating LLVM: https://github.com/Xilinx/mlir-air/pull/349

I think we should try not to divergence between our branch and git@github.com:Xilinx/mlir-aie.git

**Comment by nirvedhmeshram** [comment]
> There is a change in mlir-air main for updating LLVM: [Xilinx/mlir-air#349](https://github.com/Xilinx/mlir-air/pull/349)
> 
> I think we should try not to divergence between our branch and [git@github.com](mailto:git@github.com):Xilinx/mlir-aie.git

Yes makes sense, @Abhishek-Varma when yoou come online on Monday can we rebase https://github.com/nod-ai/mlir-aie/tree/iree_fixes on existing upstream mlir-aie

**Comment by nirvedhmeshram** [comment]
@stellaraccident do we also update the hash in https://github.com/nod-ai/iree-amd-aie/blob/main/sync_deps.py
I think @Abhishek-Varma is making this commit to make the plugin work with latest IREE. The script says its auto generated and do not edit so wanted to check how to do it.

**Comment by Abhishek-Varma** [comment]
Closing as this is not required anymore.

**Pull request closed without merging**
