### PR TITLE
Bump IREE hash to https://github.com/openxla/iree/commit/4691fc5bf37d6ba8aeac6a1c5382a595fa900f4c

### PR DESCRIPTION
**Pull request by MaheshRavishankar**

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@nirvedhmeshram please review changes to the AIETarget (I followed what was done here https://github.com/openxla/iree/commit/890b070bd94a62dc90203ed0514b212836af46ac#diff-64580f13cfa9b8f1c6e88195e8972c652d37ac302d4d5f829ac461edb0510c00)

**Comment by MaheshRavishankar** [comment]
cc @daveliddell

**Review by nirvedhmeshram — APPROVED** [review]
Thanks, LGTM!

**Comment by nirvedhmeshram** [comment]
I see some tests are failing though, let me know if you want me to take a look or someone is already on this.

**Comment by MaheshRavishankar** [comment]
> I see some tests are failing though, let me know if you want me to take a look or someone is already on this.

Thanks Nirvedh. I fixed the earlier errors, but I am seeing some e2e failures. Could you help take a look

**Comment by nirvedhmeshram** [comment]
@MaheshRavishankar can you please cherry-pick the last commit from this branch, and see if CI passes?
https://github.com/nod-ai/iree-amd-aie/tree/update_generate_script

**Comment by nirvedhmeshram** [comment]
@MaheshRavishankar I see, didnt realize I could push to your fork, nice! Looks like the CI is passing, if the changes look good to you feel free to merge this.

**Comment by MaheshRavishankar** [comment]
Thanks @nirvedhmeshram . Submitting.

**Pull request merged**
