### PR TITLE
Bump MLIR-AIR version

### PR DESCRIPTION
**Pull request by erwei-xilinx**
New MLIR-AIR features:
- air.channels can now pack parent perfectly nested loops into its sizes and strides fields.
- Packed air.channels can now lower to AIE DMA BDs to pick up the implicit loops.
- Enabled bigger lowerable matmul sizes.

### CODE REVIEW

**Comment by erwei-xilinx** [comment]
CI is failing because this PR points third_party/mlir-air to the public mlir-air repo. May I ask how should I bump the mlir-air submodule properly for this?

**Comment by newling** [comment]
Hey @erwei-xilinx , I landed this change this morning updating the air used by iree-amd-aie:

https://github.com/nod-ai/iree-amd-aie/pull/47 it describes the steps I took. 

I have now also just created a new branch in nod.ai/mlir-air: https://github.com/nod-ai/mlir-air/tree/iree_fixes_4 which brings in the changes you made to air today. For that I did:

git fetch xilinx main     # fetch from your public remote
git checkout main        
git rebase xilinx/main  
git checkout -b iree_fixes_4 
git cherry-pick iree_fixes_3    # put whatever the iree-amd-aie specific changes are on top of the latest and greatest
git push -u nodai                   # push to nod.ai 

I don't know if you have permission to push to nod.ai (the last step) @stellaraccident can probably give you permission for this. 

What I think you can do now is, in iree-amd-aie:

cd third_party/mlir-aie
git checkout iree_fixes_4
cd ../..
git add third_party 

and that should do the bump you want.

**Review by nirvedhmeshram — APPROVED** [review]
LGTM!

**Comment by nirvedhmeshram** [comment]
Not sure,  why its saying the branch has conflicts? looks like its not behind the main branch in any way?

**Comment by erwei-xilinx** [comment]
> Not sure, why its saying the branch has conflicts? looks like its not behind the main branch in any way?

Hmm it doesn't show any conflict to me? 
image

**Comment by nirvedhmeshram** [comment]
> > Not sure, why its saying the branch has conflicts? looks like its not behind the main branch in any way?
> 
> Hmm it doesn't show any conflict to me? image

Ah I was on rebase and merge, squash and merge was working so I merged it.

**Pull request merged**
