### PR TITLE
Rebase mlir-aie on main

### PR DESCRIPTION
**Pull request by newling**
This pulls in the changes on the mlir-aie main branch:

cd third_party/mlir-aie
git remote add xilinx git@github.com:Xilinx/mlir-aie.git
git fetch xilinx
git rebase xilinx/main # (has a merge conflict which I resolved)

Motivation: I'd like to start experimenting with the patch https://github.com/Xilinx/mlir-aie/pull/844

### CODE REVIEW

**Comment by nirvedhmeshram** [comment]
I think you need to have the rebase within the mlir/nod-ai repo, otherwise it will break for other users

**Comment by nirvedhmeshram** [comment]
ALso, @newling I think you want to make another branch called iree-fixes2 rather than rebasing (and hence force pushing) the old one since it will break the flow for old users when there setup looks for the commits that now wont exist.

**Comment by newling** [comment]
> > Ok, I think I understand now. I will
> > 
> > 1. rebase nod.ai/mlir-air:iree_fixes onto Xilinx/mlir-air:main,
> > 2. make PR in nod.ai/mlir-air (I don't think I have write permission)
> > 3. come back to this PR in iree-amd-aie.
> > 
> > (and will keep @Abhishek-Varma updated).
> 
> That would work, but also you should have write permissions for nod-ai/mlir-air/aie , @stellaraccident could you please add James. Thanks.

`nod-ai/mlir-air/aie` and `nod-ai/mlir-air/air` please, @stellaraccident

**Comment by stellaraccident** [comment]
Was missing the AMD team on mlir-air. Was on the other. Should work now.

**Comment by stellaraccident** [comment]
As a side note: the addition of type/attribute name fields can be done independent of llvm version bump. If on the old version, the presence of the additional field won't hurt anything, and that has been the only hard API break I've seen this month.

**Comment by makslevental** [comment]
> As a side note: the addition of type/attribute name fields can be done independent of llvm version bump. If on the old version, the presence of the additional field won't hurt anything, and that has been the only hard API break I've seen this month.

I think you're talking about this? https://github.com/Xilinx/mlir-aie/pull/809/files

**Comment by makslevental** [comment]
Just btw/fyi I bump aie's llvm dep at least once a week (and often more frequently than even that).

**Comment by newling** [comment]
> Was missing the AMD team on mlir-air. Was on the other. Should work now.

Thanks!

> As a side note: the addition of type/attribute name fields can be done independent of llvm version bump. If on the old version, the presence of the additional field won't hurt anything, and that has been the only hard API break I've seen this month.

Good point, that's what air did with https://github.com/Xilinx/mlir-air/pull/349 -- didn't actually bump llvm.

**Comment by newling** [comment]
Closing in favor of https://github.com/nod-ai/iree-amd-aie/pull/47

**Pull request closed without merging**
