### PR TITLE
Update mlir-air and mlir-aie versions

### PR DESCRIPTION
**Pull request by erwei-xilinx**

### CODE REVIEW

**Comment by erwei-xilinx** [comment]
In mlir-aie, the operation containing the LX6 program has changed from `func.func` to `aiex.runtime_sequence`. https://github.com/Xilinx/mlir-aie/pull/1640

Cc: @makslevental, @jtuyls

**Review by newling — APPROVED** [review]
Thanks!

**Review by makslevental — CHANGES_REQUESTED** [review]
Blocking for now before I have a chance to reviewv thoroughly, but I don't see the point of changing for the insertion site (lowertoaie) and the removal site (DmaToNPU). You could just leave both as is?

**Review by makslevental — APPROVED** [review]
My bad - it's air inserting and then in lowertoaie more stuff is inserted into the body. Ok that's fine.

**Pull request merged**
