### PR TITLE
[Delegate] Add transform dialect scripts for matmul+elementwise

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
The matmul test shows parity with the PDL test and runs with correct numbers e2e in local testing.
The matmul+elemetwise test generates the expected dispatch and compiles. The numerics of these are not tested as there is no delegate (cpu or AIE) for this. 
The tests use iree-compile because there is an unrelated crash in using iree-opt.

### CODE REVIEW

**Review by daveliddell — APPROVED** [review]
LGTM!

**Comment by MaheshRavishankar** [comment]
Whats the crash with `iree-opt`?

**Comment by nirvedhmeshram** [comment]
> Whats the crash with `iree-opt`?

Just needs to add a bunch of dependent dialects. AFAICS custom dispatch is only demonstarted e2e in upstream and there is no example like below in upstream

```
iree-opt --pass-pipeline="builtin.module((iree-preprocessing-transform-interpreter{transform-spec-path=/experimental/delegate/mlp_spec_matmul_elementwise.mlir}))" /proj/xsjhdstaff4/nmeshram/iree-amd-aie/experimental/delegate/matmul-elementwise-f32.mlir
```
I just tried adding the dependent dialects and running the above command and it didnt crash but to my surprise no matching happened?
I dont see any failed matches in the debug print either.

**Comment by nirvedhmeshram** [comment]
Here is a draft pull request with the dependent dialect stuff that should have solved the issue but didnt
https://github.com/iree-org/iree/pull/17354

**Comment by nirvedhmeshram** [comment]
Landing this as the iree-opt issues are unrelated to the scripts being added here and we have the iree-compile way of testing them in CI for now.

**Pull request merged**
