### PR TITLE
Use correct peano opt flags

### PR DESCRIPTION
**Pull request by makslevental**
Related to https://github.com/nod-ai/iree-amd-aie/issues/594, we are getting stuff in `input.opt.ll` that we should not be getting because we are not disabling eg vectorization at the LLVM level.

Note, copy-pasta from [llvm-aie](https://github.com/Xilinx/llvm-aie/blob/0be095354faa49985cd031661853f6d9b9b787f2/clang/lib/Driver/ToolChains/AIE.cpp#L97-L121).

### CODE REVIEW

**Review by newling — COMMENTED** [review]
What's AA?

**Review by newling — APPROVED** [review]

**Comment by nirvedhmeshram** [comment]
> What's AA?

Alias analysis
https://llvm.org/docs/Passes.html#id2

**Review by nirvedhmeshram — APPROVED** [review]
LGTM

**Comment by makslevental** [comment]
> What's AA?

god i wish i could think of something funnier than alcoholic's anonymous

**Pull request merged**
