### PR TITLE
Pruning AIETypesGen2

### PR DESCRIPTION
**Pull request by erwei-xilinx**
E2E flow example seems to work without this. Suggest pruning it for now.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Good idea...  After I can land https://github.com/nod-ai/iree-amd-aie/pull/26 we can setup a build bot and then it will be easier to check for whether this is needed or not

**Comment by MaheshRavishankar** [comment]
@erwei-xilinx do you want to rebase and give it a shot?

**Comment by erwei-xilinx** [comment]
> @erwei-xilinx do you want to rebase and give it a shot?

Sure, rebased.

**Review by nirvedhmeshram — APPROVED** [review]
LGTM!

**Pull request merged**
