### PR TITLE
[Localize ObjectFifo] Don't crash when scf.forall has no mapping

### PR DESCRIPTION
**Pull request by newling**
While we probably don't expect an scf.forall without _either_ a thread or block mapping, it's better if this pass can handle the case.

### CODE REVIEW

**Comment by newling** [comment]
The original code:
```
 if (isa<mlir::gpu::GPUThreadMappingAttr>(
          *forallOp.getMapping()->getValue().begin())) {
```

doesn't check if if `forallOp` even has a mapping, an optional attribute. So there is a segfault on getValue(). 

This PR is exactly equivalent to just adding a `has_value()` check in. The rest of the change is replacing recursion.

**Comment by jtuyls** [comment]
> The original code:
> 
> ```
>  if (isa<mlir::gpu::GPUThreadMappingAttr>(
>           *forallOp.getMapping()->getValue().begin())) {
> ```
> 
> doesn't check if `forallOp` has a mapping, an optional attribute. So there is a segfault on getValue().
> 
> This PR is exactly equivalent to just adding a `has_value()` check in. The rest of the change is replacing recursion.

But it won't throw an error?

**Comment by newling** [comment]
> > The original code:
> > ```
> >  if (isa<mlir::gpu::GPUThreadMappingAttr>(
> >           *forallOp.getMapping()->getValue().begin())) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > doesn't check if `forallOp` has a mapping, an optional attribute. So there is a segfault on getValue().
> > This PR is exactly equivalent to just adding a `has_value()` check in. The rest of the change is replacing recursion.
> 
> But it won't throw an error?

Not sure I understand question, are you suggesting I make a change to the logic? All this PR does is what was done in 

https://github.com/nod-ai/iree-amd-aie/commit/883ee07732ece0b3cccdcd871c1b7d4c3eeebed2 

w.r.t. mapping on scf.forall.

**Comment by jtuyls** [comment]
> > > The original code:
> > > ```
> > >  if (isa<mlir::gpu::GPUThreadMappingAttr>(
> > >           *forallOp.getMapping()->getValue().begin())) {
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > doesn't check if `forallOp` has a mapping, an optional attribute. So there is a segfault on getValue().
> > > This PR is exactly equivalent to just adding a `has_value()` check in. The rest of the change is replacing recursion.
> > 
> > 
> > But it won't throw an error?
> 
> Not sure I understand question, are you suggesting I make a change to the logic? All this PR does is what was done in
> 
> [883ee07](https://github.com/nod-ai/iree-amd-aie/commit/883ee07732ece0b3cccdcd871c1b7d4c3eeebed2)
> 
> w.r.t. mapping on scf.forall.

Yeah, the PR says 'Don't crash when scf.forall has no mapping '. I agree there shouldn't be a segfault, but now the pass will just continue and then at some point there will be an error/crash again, at a point where it might not be clear that this is the root issue? I think the correct behaviour would be to throw an error in this pass if no scf.forall ops with thread mapping were found.

**Comment by newling** [comment]
> > > > The original code:
> > > > ```
> > > >  if (isa<mlir::gpu::GPUThreadMappingAttr>(
> > > >           *forallOp.getMapping()->getValue().begin())) {
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > doesn't check if `forallOp` has a mapping, an optional attribute. So there is a segfault on getValue().
> > > > This PR is exactly equivalent to just adding a `has_value()` check in. The rest of the change is replacing recursion.
> > > 
> > > 
> > > But it won't throw an error?
> > 
> > 
> > Not sure I understand question, are you suggesting I make a change to the logic? All this PR does is what was done in
> > [883ee07](https://github.com/nod-ai/iree-amd-aie/commit/883ee07732ece0b3cccdcd871c1b7d4c3eeebed2)
> > w.r.t. mapping on scf.forall.
> 
> Yeah, the PR says 'Don't crash when scf.forall has no mapping '. I agree there shouldn't be a segfault, but now the pass will just continue and then at some point there will be an error/crash again, at a point where it might not be clear that this is the root issue? I think the correct behaviour would be to throw an error in this pass if no scf.forall ops with thread mapping were found.

I agree with your overall design idea, but this PR doesn't change the behavior. It is exactly equivalent to https://github.com/nod-ai/iree-amd-aie/pull/669/files

**Comment by jtuyls** [comment]
>  This isn't about the case where there is no scf.forall with a thread mapping, it's about the case where there is an scf.forall with no mapping (thread or block).

Ah, I see, like a case with some `scf.forall` ops with mapping and others without?

**Review by jtuyls — APPROVED** [review]

**Comment by newling** [comment]
> > This isn't about the case where there is no scf.forall with a thread mapping, it's about the case where there is an scf.forall with no mapping (thread or block).
> 
> Ah, I see, like a case with some `scf.forall` ops with mapping and others without?

Yes, that's the edge case being fixed

**Pull request merged**
