### PR TITLE
Add support for AIE translator

### PR DESCRIPTION
**Pull request by yzhang93**

### CODE REVIEW

**Comment by makslevental** [comment]
Just curious: what's the plan here? To emit AIE dialect and then use `aie-translate` to emit LLVM IR? Or to actually use passes in AIE?

**Review by MaheshRavishankar — COMMENTED** [review]
So we dont have tests here yet right?

**Comment by MaheshRavishankar** [comment]
> Just curious: what's the plan here? To emit AIE dialect and then use `aie-translate` to emit LLVM IR? Or to actually use passes in AIE?

This is just an off-ramp we are using to connect to some other flows. We have this in the short term to check for correctness and build up some functionality that the other flows expect (and will eventually be needed). Long term we should just be able to generate LLVM IR and compile it using LLVM to native executable.... there are a few steps to get us there, but thats what we are hoping for.

**Comment by yzhang93** [comment]
> So we dont have tests here yet right?

Just added the tests. It passed if you run `ctest -R amd-aie`.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
