### PR TITLE
Bump IREE to 8e5f218a1d73c39ccdebb4a1d19225d5329cc6f0

### PR DESCRIPTION
**Pull request by yzhang93**
Also bump MLIR-AIR to 8fe05179d83f04cf56965ae55da0f476ec7431ed

### CODE REVIEW

**Comment by makslevental** [comment]
I can figure out the reason for the segfault on Monday

**Comment by yzhang93** [comment]
> I can figure out the reason for the segfault on Monday

Thanks! It might relate to this change in IREE? https://github.com/iree-org/iree/commit/0077358221e3fd2a52d114115ac9b9d17089fc16

**Comment by makslevental** [comment]
The failing tests are on Linux where the XRT-LITE HAL is used but you're fixing/changing the XRT HAL...

**Comment by yzhang93** [comment]
> The failing tests are on Linux where the XRT-LITE HAL is used but you're fixing/changing the XRT HAL...

There were windows failures as well https://github.com/nod-ai/iree-amd-aie/actions/runs/11749085186/job/32734566694, so the xrt hal changes were a fix for that. Linux failure has not been solved yet.

**Comment by makslevental** [comment]
> , which I thought you'll help take a look.

Yup yup

**Pull request merged**
