### PR TITLE
Add pass to combine strided ops like NPU DMA ops

### PR DESCRIPTION
**Pull request by jtuyls**
Combines strided operations, specifically `amdaie.npu.dma_cpy_nd` for now. The goal of this is to reduce the number of control code instructions, which improves performance and should help with avoiding resource issues as well (see https://github.com/nod-ai/iree-amd-aie/issues/556).

Example:

The following `amdaie.npu.dma_cpy_nd` operations can be combined into a single one as they have the same core access pattern (size: `16` and stride: `1`), but different offsets.

```
%0 = amdaie.circular_dma_cpy_nd...
%1 = amdaie.npu.dma_cpy_nd %0([] [] [], [0] [16] [1])
%2 = amdaie.npu.dma_cpy_nd %0([] [] [], [0, 32] [2, 16] [32, 1])
%3 = amdaie.npu.dma_cpy_nd %0([] [] [], [96] [16] [1])
```

First, `%1` and `%2` are combined into a new `amdaie.npu.dma_cpy_nd` operation with offset `0` from `%1`, and the outermost size incremented from 2 to 3 to keep the transmitted data equal to the separate instructions.

```
%new1 = amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0] [3, 16] [32, 1])
%3 = amdaie.npu.dma_cpy_nd %0([] [] [], [96] [16] [1])
```

Afterwards, `%new1` and `%3` can be combined into `%new2`, with the outermost size increment from 3 to 4:

```
%new2 = amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0] [4, 16] [32, 1])
```

### CODE REVIEW

**Comment by nirvedhmeshram** [comment]
Since the tests are passing it means this specific issue is not happening yet but it is still something to think about.  `amdaie.npu.dma_cpy_nd` basically consumes  `hal.interface.binding.subspan` which essentially will become the buffer arguments we pass to the kernel at runtime, so this combining is breaking the contract we have with the host code?

As an aside I am interested in understanding if the combination did happen in any of the e2e tests? If it did, I guess the combination takes into account the multiple bindings and I am not seeing something?

**Comment by jtuyls** [comment]
> amdaie.npu.dma_cpy_nd basically consumes hal.interface.binding.subspan which essentially will become the buffer arguments we pass to the kernel at runtime, so this combining is breaking the contract we have with the host code?

Could you elaborate? I don't think the combination breaks anything with regard to `hal.interface.binding.subspan`.

> As an aside I am interested in understanding if the combination did happen in any of the e2e tests? If it did, I guess the combination takes into account the multiple bindings and I am not seeing something?

Yes, it does happen for sure because of the peeling, i.e. prolog, main, epilog will have NPU DMA instructions which can be combined.

**Comment by nirvedhmeshram** [comment]
> Could you elaborate? I don't think the combination breaks anything with regard to hal.interface.binding.subspan.

so my thinking is these ops will become something like this
```
  func.func @matmul_8_4_8_dispatch_0_matmul_8x4x8_f32(%arg0: memref<8x8xf32>, %arg1: memref<8x4xf32>, %arg2: memref<8x4xf32>) {
    aiex.npu.dma_memcpy_nd(0, 0, %arg2[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 0 : i64, issue_token = true, metadata = @obj7} : memref<8x4xf32>
    aiex.npu.dma_memcpy_nd(0, 0, %arg1[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 1 : i64, issue_token = true, metadata = @obj1} : memref<8x4xf32>
    aiex.npu.dma_memcpy_nd(0, 0, %arg0[0, 0, 0, 0][1, 1, 1, 64][0, 0, 0, 1]) {id = 2 : i64, issue_token = true, metadata = @obj0} : memref<8x8xf32>
    aiex.npu.dma_wait {symbol = @obj7}
    aiex.npu.dma_wait {symbol = @obj1}
    aiex.npu.dma_wait {symbol = @obj0}
    return
  }
  ```
  each `aiex.npu.dma_memcpy_nd` is a runtime buffer argument, and I am wondering what happens if they get combined without the corresponding runtime adjustments..
  
 > Yes, it does happen for sure because of the peeling, i.e. prolog, main, epilog will have NPU DMA instructions which can be combined.
  
  Ah maybe you are combining for the same dma temporally but you have a safeguard to make sure the above case I mentioned will not become one copy?

**Comment by jtuyls** [comment]
> so my thinking is these ops will become something like this
> 
> ```
>   func.func @matmul_8_4_8_dispatch_0_matmul_8x4x8_f32(%arg0: memref<8x8xf32>, %arg1: memref<8x4xf32>, %arg2: memref<8x4xf32>) {
>     aiex.npu.dma_memcpy_nd(0, 0, %arg2[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 0 : i64, issue_token = true, metadata = @obj7} : memref<8x4xf32>
>     aiex.npu.dma_memcpy_nd(0, 0, %arg1[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 1 : i64, issue_token = true, metadata = @obj1} : memref<8x4xf32>
>     aiex.npu.dma_memcpy_nd(0, 0, %arg0[0, 0, 0, 0][1, 1, 1, 64][0, 0, 0, 1]) {id = 2 : i64, issue_token = true, metadata = @obj0} : memref<8x8xf32>
>     aiex.npu.dma_wait {symbol = @obj7}
>     aiex.npu.dma_wait {symbol = @obj1}
>     aiex.npu.dma_wait {symbol = @obj0}
>     return
>   }
> ```
> > Yes, it does happen for sure because of the peeling, i.e. prolog, main, epilog will have NPU DMA instructions which can be combined.
> 
> Ah maybe you are combining for the same dma temporally but you have a safeguard to make sure the above case I mentioned will not become one copy?

This pass does not operate on `aiex.npu.dma_memcpy_nd`, but on `amdaie.npu.dma_cpy_nd` and it will consider the input DMA argument so it won't combine across different circular DMA operations, so what's you're describing can't happen.

**Review by nirvedhmeshram — APPROVED** [review]
LGTM!

**Comment by jtuyls** [comment]
> > so my thinking is these ops will become something like this
> > ```
> >   func.func @matmul_8_4_8_dispatch_0_matmul_8x4x8_f32(%arg0: memref<8x8xf32>, %arg1: memref<8x4xf32>, %arg2: memref<8x4xf32>) {
> >     aiex.npu.dma_memcpy_nd(0, 0, %arg2[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 0 : i64, issue_token = true, metadata = @obj7} : memref<8x4xf32>
> >     aiex.npu.dma_memcpy_nd(0, 0, %arg1[0, 0, 0, 0][1, 1, 1, 32][0, 0, 0, 1]) {id = 1 : i64, issue_token = true, metadata = @obj1} : memref<8x4xf32>
> >     aiex.npu.dma_memcpy_nd(0, 0, %arg0[0, 0, 0, 0][1, 1, 1, 64][0, 0, 0, 1]) {id = 2 : i64, issue_token = true, metadata = @obj0} : memref<8x8xf32>
> >     aiex.npu.dma_wait {symbol = @obj7}
> >     aiex.npu.dma_wait {symbol = @obj1}
> >     aiex.npu.dma_wait {symbol = @obj0}
> >     return
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Yes, it does happen for sure because of the peeling, i.e. prolog, main, epilog will have NPU DMA instructions which can be combined.
> > 
> > 
> > Ah maybe you are combining for the same dma temporally but you have a safeguard to make sure the above case I mentioned will not become one copy?
> 
> This pass does not operate on `aiex.npu.dma_memcpy_nd`, but on `amdaie.npu.dma_cpy_nd` and it will consider the input DMA argument so it won't combine across different circular DMA operations, so what's you're describing can't happen.

@nirvedhmeshram FYI, I added a testcase for this: https://github.com/nod-ai/iree-amd-aie/pull/606/files#diff-9683cd8b32cf91028abba50f48d52baa6aff7af67b1c54c4ff28d8c88f718acfR31

**Review by Abhishek-Varma — APPROVED** [review]
Small nit.

LGTM!

**Pull request merged**
