### PR TITLE
Add enum options to target lowering tablegen

### PR DESCRIPTION
**Pull request by jtuyls**
@Abhishek-Varma Could you help review?

### CODE REVIEW

**Comment by jtuyls** [comment]
cc @frafranz

**Review by MaheshRavishankar — APPROVED** [review]
Nice!

**Review by Abhishek-Varma — APPROVED** [review]
LGTM! Thanks for this!

**Comment by jtuyls** [comment]
@Abhishek-Varma Can this PR be merged?

**Comment by Abhishek-Varma** [comment]
> @Abhishek-Varma Can this PR be merged?

Absolutely!

Can you rebase with current master and force-push? I'll get this in once the CI passes again.

**Comment by jtuyls** [comment]
> > @Abhishek-Varma Can this PR be merged?
> 
> Absolutely!
> 
> Can you rebase with current master and force-push? I'll get this in once the CI passes again.

I updated with main.

**Pull request merged**
