### PR TITLE
Add an e2e matmul transpose test 

### PR DESCRIPTION
**Pull request by newling**
Currently fails to compile (error message copied into test).

### CODE REVIEW

**Review by yzhang93 — CHANGES_REQUESTED** [review]
It's useful if you also add another test for matmul_transpose_b with i32 type.

**Comment by yzhang93** [comment]
Can you try to add vectorization passes and see if bf16 ci pass after that? @erwei-xilinx reported peano + bf16 can only work in ci with vectorization passes.

**Comment by erwei-xilinx** [comment]
> Can you try to add vectorization passes and see if bf16 ci pass after that? @erwei-xilinx reported peano + bf16 can only work in ci with vectorization passes.

No I meant the pack-peel pipeline which is missing vectorization passes. The transpose pipeline is still using pad-pack which already has vectorization.

**Comment by yzhang93** [comment]
> > Can you try to add vectorization passes and see if bf16 ci pass after that? @erwei-xilinx reported peano + bf16 can only work in ci with vectorization passes.
> 
> No I meant the pack-peel pipeline which is missing vectorization passes. The transpose pipeline is still using pad-pack which already has vectorization.

A good point! @newling We should also add matmul transpose test for pack-peel pipeline. If that works with vectorization, we don't have to waste time fixing failure for pad-pack.

**Comment by newling** [comment]
Hey @yzhang93 and @erwei-xilinx PR https://github.com/nod-ai/iree-amd-aie/pull/319 adds vectorization to the pack peel pipeline, but the pipeline needs work to make vectorization work. So tests are not fully enabled in https://github.com/nod-ai/iree-amd-aie/pull/319

**Comment by erwei-xilinx** [comment]
@newling the error comes from AIR failing to analyze a data access pattern with vectorized code. If `linalg.generic` can remain at AIR input then the test should pass. I wonder how difficult do you think it is to move the vectorization passes to after, or in the middle of, AIR passes?

**Comment by newling** [comment]
> @newling the error comes from AIR failing to analyze a data access pattern with vectorized code. If `linalg.generic` can remain at AIR input then the test should pass. I wonder how difficult do you think it is to move the vectorization passes to after, or in the middle of, AIR passes?

I think the vectorization pass needs to happen before bufferization, but I'm not sure.

**Comment by newling** [comment]
@erwei-xilinx @yzhang93 @MaheshRavishankar 

I tried permuting the order in which vectorization and bufferization happen from:


```
appendVectorizationToPipeline(funcPassManager);
addAMDAIEBufferizePasses(funcPassManager);                                                                                                                                                                 ```

to 

```
addAMDAIEBufferizePasses(funcPassManager);                                                                                                                                                                
appendVectorizationToPipeline(funcPassManager);
```

but the vectorization pass fails. I think it crashes in `linalg::tileLinalgOp(rewriter, genericOp, opts);` (assertion error about incorrect number of results). 

So hopefully you can find another solution, because running vectorization later doesn't seem like it will be a quick-fix. Hopefully the L1 memory can be created to be the correct size at construction..

**Comment by erwei-xilinx** [comment]
> @erwei-xilinx @yzhang93 @MaheshRavishankar
> 
> I tried permuting the order in which vectorization and bufferization happen from:

Thanks for trying that, @newling . I put together this PR to AIR which attempts to analyze the data access pattern of post-vectorization kernel code: https://github.com/Xilinx/mlir-air/pull/565 This will actually get the CI to pass for pack-peel bf16 GEMMs, but currently causing pad-pack to fail... Will keep looking into that issue tomorrow.

**Comment by newling** [comment]
Thanks Erwei. Yes I think ideally we'd have transpose working on both pipelines.

**Review by yzhang93 — APPROVED** [review]

**Pull request merged**
